### PR TITLE
Update nf-jarvice to 0.7.0

### PR DESCRIPTION
**Pull request by oxedions**
Update nf-jarvice to 0.7.0 with better error handling.

### CODE REVIEW

**Review by pditommaso — APPROVED** [review]
OK, thanks for contributing this

**Review by pditommaso — CHANGES_REQUESTED** [review]
However it looks there's a conflict. Have published it twice using the same version number?

**Comment by oxedions** [comment]
Indeed ! Sorry, I missed that, and I was traveling 😊

**Review by pditommaso — APPROVED** [review]

**Comment by pditommaso** [comment]
Well done

**Pull request merged**
