### PR TITLE
Temporarily remove version 2.0.0 to stop all pipelines breaking :grin: 

### PR DESCRIPTION
**Pull request by nvnieuwk**

### CODE REVIEW

**Review by ewels — APPROVED** [review]
Sorry about this! To be returned soon..

**Comment by ewels** [comment]
Are there any pipelines that _have_ updated that will now break if we revert this?

**Comment by nvnieuwk** [comment]
I don't think there are any yet, maybe Maxime updated one though

**Comment by ewels** [comment]
@maxulysse - be aware ☝🏻

**Comment by ewels** [comment]
Basically need to wait until the majority of search hits [here](https://github.com/search?q=org%3Anf-core+path%3Anextflow.config+nf-validation&type=code) show a pinned version.

When someone gets a chance, it'd be good to write these up as an issue on nf-core/tools with a checklist, then work through them with PRs / Slack nudges etc. to pin the versions and get patch releases out.

**Pull request merged**
