### PR TITLE
release nf-snowflake 0.6.0

### PR DESCRIPTION
**Pull request by sfc-gh-hyu**
Running nextflow against Snowflake SnowparkContainerService

### CODE REVIEW

**Comment by pditommaso** [comment]
Hi, thanks a lot for contributing this. For the sake of the community it would be nice to add a minimal "Get started" section the [project readme file](https://github.com/Snowflake-Labs/nf-snowflake/blob/main/README.md).

**Comment by sfc-gh-hyu** [comment]
@pditommaso Sure, I do plan to spend more time on documentation.

**Comment by pditommaso** [comment]
Nice@! looking forward for it to approve it.

**Comment by sfc-gh-hyu** [comment]
@pditommaso I added a quickstart section in the original plugin repo.

**Comment by pditommaso** [comment]
Much appreciated!

**Review by pditommaso — APPROVED** [review]

**Pull request merged**
