### PR TITLE
add first version of nf-parquet

### PR DESCRIPTION
**Pull request by jagedn**
I would like to include a new plugin to read/write parquet files

### CODE REVIEW

**Comment by pditommaso** [comment]
Is this the same of [this](https://github.com/nextflow-io/nf-parquet)? maybe they can be merged in the same repo hosted on nextflow-io (you will be the admin)?

**Comment by jagedn** [comment]
didn't realize there were an initial proposal for this plugin!!!

I'll try to fork it and prepare a (mega) PR

**Comment by pditommaso** [comment]
🙌

**Comment by bentsherman** [comment]
I don't think I ever got it to work, so feel free to throw out my code entirely

**Pull request closed without merging**
