### PR TITLE
Add JSON snippet for latest nf-nomad release

### PR DESCRIPTION
**Pull request by abhi18av**
Hi team 👋 

Adding another release for the `nf-nomad` plugin for your consideration.

CC @tomiles @jagedn

### CODE REVIEW

**Review by matthdsm — COMMENTED** [review]
🚀

**Comment by matthdsm** [comment]
@bentsherman , sorry to bother, but can we have an approval here?

**Comment by bentsherman** [comment]
sorry for the delay

**Comment by abhi18av** [comment]
Thanks guys! :)

**Pull request merged**
